version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(funcName)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/seek.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/seek_errors.log
    maxBytes: 10485760  # 10MB
    backupCount: 3

loggers:
  src.services:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  src.api:
    level: INFO
    handlers: [console, file]
    propagate: no

  supabase:
    level: WARNING
    handlers: [console, file]
    propagate: no

root:
  level: INFO
  handlers: [console, file, error_file]